dist: xenial
services:
  - docker
cache:
  directories:
    - .autoconf
before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - wget https://product-dist.ballerina.io/downloads/0.991.0/ballerina-linux-installer-x64-0.991.0.deb
  - sudo dpkg -i ballerina*.deb
  - wget https://wso2.org/jenkins/view/cellery/job/cellery/job/sdk/lastSuccessfulBuild/artifact/installers/ubuntu-x64/target/*zip*/target.zip
  - unzip target.zip
  - sudo dpkg -i target/cellery*.deb
  - mkdir ${HOME}/.kube
  - cp ${TRAVIS_BUILD_DIR}/kubeconfig ${HOME}/.kube/config
  - kubectl config set clusters.k8s.certificate-authority-data "$KUBE_CLUSTER_CERTIFICATE"
  - kubectl config set users.teleport.client-certificate-data "$KUBE_CLIENT_CERTIFICATE"
  - kubectl config set users.teleport.client-key-data "$KUBE_CLIENT_KEY"
  - kubectl cluster-info
script:
  - cat ${HOME}/.kube/config
  - cellery build foo.bal myorg/foo:${TRAVIS_COMMIT}
  - cellery update foo myorg/foo:${TRAVIS_COMMIT}